function initPapef(){
  if(document.getElementById('section-ejercicio-papef')) return;
  const movementMenu=[...document.querySelectorAll('.nav-group-title')].find(b=>b.textContent.includes('Movimiento y Ejercicio'))?.nextElementSibling;
  if(movementMenu){const a=document.createElement('a');a.href='#';a.textContent='🌿 PAPEF: ejercicio con salud';a.onclick=e=>{e.preventDefault();showSection('ejercicio-papef')};movementMenu.prepend(a)}
  const main=document.getElementById('contentArea'); if(!main) return;
  const section=document.createElement('section'); section.className='section'; section.id='section-ejercicio-papef';
  section.innerHTML=`<div class="section-header"><button class="back-btn" onclick="showSection('home')">← Inicio</button><h2>🌿 PAPEF · Ejercicio con salud</h2></div><div class="content-card"><div class="papef-page">

  <div class="papef-hero"><div><span class="papef-kicker">ANDALUCÍA EN FORMA · SALUD + DEPORTE</span><h3>¿Y si el ejercicio formara parte de tu tratamiento?</h3><p>Eso es, en esencia, el <strong>PAPEF</strong>: un puente entre el sistema sanitario y los recursos deportivos de tu municipio para que, cuando lo necesites, no te quedes solo con un “tienes que moverte más”.</p><p>El objetivo es pasar del consejo general a un plan <strong>seguro, personalizado y acompañado</strong>.</p><div class="papef-mini-note">💬 Aquí no vamos a repetirte cuántos minutos de cardio o cuántas sesiones de fuerza hacer: eso ya lo tienes explicado en los demás apartados de Movimiento y Ejercicio. Aquí te contamos <b>qué aporta PAPEF y cómo puedes acceder a sus recursos</b>.</div></div><img src="img/papef-circuito.svg" alt="Circuito PAPEF desde la valoración sanitaria hasta un plan de ejercicio adaptado"></div>

  <section class="papef-story"><div><span class="papef-kicker">PAPEF EN 20 SEGUNDOS</span><h3>Del “muévete más” al “vamos a ver qué necesitas”</h3><p>Imagina que tienes diabetes, hipertensión, obesidad, dolor, fragilidad o simplemente llevas mucho tiempo sin hacer ejercicio y no sabes por dónde empezar. Tu profesional sanitario puede valorar tu situación y, si cumples criterios y existe recurso disponible, <strong>derivarte a una Unidad Activa de Ejercicio Físico (UAEF)</strong>.</p><p>Allí, un profesional cualificado en Ciencias de la Actividad Física y del Deporte puede evaluar tu condición física y convertir esa recomendación en un programa que tenga sentido para ti.</p></div><img src="img/papef-uaef.svg" alt="Coordinación entre profesionales sanitarios y del ejercicio físico"></section>

  <h3>Tu recorrido, sin líos</h3><div class="papef-route"><article><span>1</span><strong>Te valoran</strong><p>Salud, actividad actual, limitaciones y necesidades.</p></article><article><span>2</span><strong>Deciden contigo</strong><p>No todo el mundo necesita lo mismo: consejo, seguimiento o prescripción.</p></article><article><span>3</span><strong>Si procede, te derivan</strong><p>La UAEF conecta el ámbito sanitario con el deportivo municipal.</p></article><article><span>4</span><strong>Te evalúan</strong><p>Se estudia tu punto de partida para ajustar el ejercicio.</p></article><article><span>5</span><strong>Se revisa</strong><p>El plan puede cambiar según evolución, tolerancia y objetivos.</p></article></div>

  <div class="papef-key"><span>✨</span><div><strong>La clave no es hacer “el ejercicio perfecto”</strong><p>Es encontrar una actividad que puedas realizar con seguridad, que encaje en tu vida y que pueda progresar contigo. PAPEF intenta que salud y deporte hablen el mismo idioma.</p></div></div>

  <section class="papef-uaef"><span class="papef-kicker">¿PARA QUIÉN PUEDE SER ESPECIALMENTE ÚTIL?</span><h3>Cuando empezar por tu cuenta no es tan sencillo</h3><div class="papef-benefits"><article><span>🫀</span><strong>Riesgo cardiovascular</strong><p>Cuando conviene ajustar mejor intensidad, progresión y seguimiento.</p></article><article><span>🩸</span><strong>Diabetes tipo 2</strong><p>El ejercicio puede formar parte del abordaje terapéutico y requiere individualización.</p></article><article><span>⚖️</span><strong>Sobrepeso u obesidad</strong><p>Especialmente si hay baja condición física, comorbilidades o miedo a empezar.</p></article><article><span>🦴</span><strong>Personas mayores o frágiles</strong><p>Para trabajar capacidad funcional con una progresión adaptada.</p></article><article><span>🧩</span><strong>Enfermedad crónica</strong><p>Cuando la situación clínica aconseja una prescripción más específica.</p></article><article><span>🌱</span><strong>Inactividad mantenida</strong><p>Para convertir un comienzo difícil en pasos pequeños y realistas.</p></article></div></section>

  <section class="papef-map"><div class="papef-map-head"><div><span class="papef-kicker">MAPA OFICIAL · RED PAPEF</span><h3>Encuentra tu Unidad Activa de Ejercicio Físico</h3><p>La propia Red PAPEF mantiene un mapa público con las <strong>UAEF disponibles en Andalucía</strong>. Como estas unidades dependen de entidades locales y la red sigue creciendo, mostramos el mapa oficial en lugar de copiar una lista que podría quedarse desactualizada.</p></div><a href="https://redpapef.com/" target="_blank" rel="noopener">Abrir Red PAPEF ↗</a></div><div class="papef-map-frame"><iframe title="Mapa oficial de Unidades Activas de Ejercicio Físico de Andalucía" src="https://www.google.com/maps/d/u/0/embed?ehbc=2E312F&mid=1s-W-dfJ-kuCKbv7KVOn8OHbQUBZUQsk&noprof=1" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div><p class="papef-map-note">📍 <strong>Consejo:</strong> amplía el mapa y pulsa sobre los marcadores para consultar la información publicada por la Red PAPEF. La disponibilidad y funcionamiento pueden cambiar según cada municipio.</p></section>

  <section class="papef-digital"><div><span>📱</span><h3>¿Y ActiVital qué pinta aquí?</h3><p>Es la herramienta digital vinculada al PAPEF que permite apoyar el diseño, seguimiento y evaluación de los programas, además de facilitar la coordinación de las UAEF. Para el paciente puede servir como apoyo para consultar y seguir su programa cuando esté incorporado al circuito.</p></div><a href="https://activital.ugr.es/" target="_blank" rel="noopener">Conocer ActiVital ↗</a></section>

  <details class="papef-special"><summary>Quiero preguntar por PAPEF en mi centro de salud. ¿Qué digo?</summary><div><p>Puedes plantearlo de forma sencilla: <strong>“Quiero empezar a hacer ejercicio, pero por mi situación de salud me gustaría saber si puedo beneficiarme del PAPEF o de una UAEF de mi municipio.”</strong></p><p>La derivación no es automática ni necesaria para todas las personas: depende de la valoración profesional, de tus necesidades y de los recursos disponibles en tu zona.</p></div></details>

  <details class="papef-sources"><summary>Fuentes y actualización</summary><ul><li><b>Junta de Andalucía.</b> Plan Andaluz de Prescripción de Ejercicio Físico (Andalucía en Forma), 2023–2030.</li><li><b>Junta de Andalucía, 2024.</b> Guía para profesionales sobre recomendación de actividad física y prescripción de ejercicio físico para la salud.</li><li><b>Red PAPEF.</b> Mapa público de UAEF disponibles en Andalucía.</li><li><b>ActiVital.</b> Plataforma digital de apoyo al PAPEF.</li><li><b>BOJA 2025.</b> Nueva convocatoria para entidades locales destinada a la creación de UAEF.</li></ul><p>Última revisión del apartado: septiembre de 2026. El mapa se carga desde la fuente oficial para reflejar sus actualizaciones.</p></details>

  </div></div>`; main.appendChild(section);
  const homeCard=[...document.querySelectorAll('.home-card')].find(c=>c.textContent.includes('Movimiento')); if(homeCard) homeCard.onclick=()=>showSection('ejercicio-papef');
}
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',initPapef); else initPapef();