function initPapef(){
  if(document.getElementById('section-ejercicio-papef')) return;
  const movementMenu=[...document.querySelectorAll('.nav-group-title')].find(b=>b.textContent.includes('Movimiento y Ejercicio'))?.nextElementSibling;
  if(movementMenu){const a=document.createElement('a');a.href='#';a.textContent='🌿 PAPEF: ejercicio con salud';a.onclick=e=>{e.preventDefault();showSection('ejercicio-papef')};movementMenu.prepend(a)}
  const main=document.getElementById('contentArea'); if(!main) return;
  const section=document.createElement('section');section.className='section';section.id='section-ejercicio-papef';
  section.innerHTML=`<div class="section-header"><button class="back-btn" onclick="showSection('home')">← Inicio</button><h2>🌿 PAPEF · Ejercicio con salud</h2></div><div class="content-card"><div class="papef-page">
  <div class="papef-hero"><div><span class="papef-kicker">PLAN ANDALUZ · SALUD + DEPORTE</span><h3>El ejercicio también se puede “prescribir”</h3><p>El <strong>PAPEF</strong> es el Plan Andaluz de Prescripción de Actividad y Ejercicio Físico. Busca que más personas se muevan de forma <strong>segura, progresiva, individualizada y coordinada</strong> entre profesionales sanitarios y de la actividad física.</p><p>No se trata de decirte “haz deporte” y ya. Se valora tu situación y, cuando procede, se diseña una dosis de ejercicio adaptada a tu salud, capacidad, preferencias y punto de partida.</p></div><img src="img/papef-endonutri.svg" alt="Personas realizando actividad física con acompañamiento sanitario y deportivo"></div>
  <div class="papef-key"><span>🌱</span><div><strong>Si ahora haces poco, tienes mucho que ganar</strong><p>Pasar de no moverse a moverse un poco ya importa. No necesitas empezar siendo deportista: <strong>cada movimiento cuenta</strong>.</p></div></div>
  <h3>¿Cómo funciona?</h3><div class="papef-route"><article><span>1</span><strong>Valorar</strong><p>Actividad, sedentarismo, salud, riesgos, limitaciones y motivación.</p></article><article><span>2</span><strong>Decidir</strong><p>Consejo, intervención o prescripción individualizada según cada persona.</p></article><article><span>3</span><strong>Prescribir y derivar</strong><p>Cuando procede, Atención Primaria puede derivar a una Unidad Activa de Ejercicio Físico (UAEF).</p></article><article><span>4</span><strong>Entrenar con supervisión</strong><p>El profesional adapta el programa y controla la progresión.</p></article><article><span>5</span><strong>Seguir y ajustar</strong><p>Se revisan tolerancia, condición física, resultados y objetivos.</p></article></div>
  <section class="papef-uaef"><span class="papef-kicker">UAEF</span><h3>De la recomendación a un plan real</h3><p>Las <strong>Unidades Activas de Ejercicio Físico</strong> ofrecen ejercicio individualizado y supervisado, coordinado con Atención Primaria. Según la persona pueden valorarse fuerza, resistencia cardiovascular, equilibrio, agilidad, tensión arterial y otros parámetros.</p><div class="papef-team"><span>🩺</span><div><b>Profesional sanitario</b><br><i>valora · prescribe · deriva</i></div><strong>＋</strong><div>🏃 <b>Educador físico-deportivo</b><br><i>evalúa · programa · supervisa</i></div></div></section>
  <h3>¿Qué beneficios buscamos?</h3><div class="papef-benefits"><article><span>♥</span><strong>Corazón y tensión</strong><p>Mejor capacidad cardiorrespiratoria y control de factores de riesgo.</p></article><article><span>🩸</span><strong>Glucosa y metabolismo</strong><p>Mejora de la sensibilidad a la insulina y del control metabólico.</p></article><article><span>💪</span><strong>Fuerza y función</strong><p>Más capacidad para caminar, levantarte, cargar y hacer tareas cotidianas.</p></article><article><span>⚖️</span><strong>Obesidad</strong><p>Ayuda a reducir grasa, conservar músculo y mantener mejor la pérdida de peso junto al tratamiento nutricional.</p></article><article><span>🧠</span><strong>Bienestar</strong><p>Beneficios en ánimo, sueño, autonomía y calidad de vida.</p></article><article><span>🦴</span><strong>Envejecer mejor</strong><p>Fuerza, equilibrio y ejercicio multicomponente ayudan a preservar independencia.</p></article></div>
  <section class="papef-dose"><span class="papef-kicker">GUÍA BÁSICA PARA ADULTOS</span><h3>La “dosis” semanal de referencia</h3><div class="papef-dose-grid"><article><strong>150–300</strong><span>min/semana</span><p>actividad aeróbica <b>moderada</b></p></article><em>o</em><article><strong>75–150</strong><span>min/semana</span><p>actividad <b>vigorosa</b></p></article><em>＋</em><article><strong>≥2</strong><span>días/semana</span><p><b>fuerza</b> de grandes grupos musculares</p></article></div><p class="papef-dose-note">Si partes de cero, empieza por una cantidad que puedas repetir y aumenta gradualmente. En mayores, fragilidad o riesgo de caídas cobra especial importancia el trabajo multicomponente: fuerza + equilibrio + resistencia + movilidad.</p></section>
  <h3>¿Moderado o vigoroso? Usa el “test del habla”</h3><div class="papef-intensity"><article><span>🙂</span><strong>Suave</strong><p>Puedes hablar y cantar sin dificultad.</p></article><article><span>🚶</span><strong>Moderado</strong><p>Puedes hablar en frases, pero cantar ya cuesta.</p></article><article><span>⚡</span><strong>Vigoroso</strong><p>Respiras fuerte y solo puedes decir pocas palabras seguidas.</p></article></div>
  <section class="papef-week"><span class="papef-kicker">EJEMPLO, NO RECETA UNIVERSAL</span><h3>Una semana sencilla para empezar</h3><div class="papef-week-grid"><article><b>Lunes</b><p>20–30 min de paseo ligero + movilidad.</p></article><article><b>Martes</b><p>Fuerza de cuerpo completo: 5–8 ejercicios, 1–3 series.</p></article><article><b>Miércoles</b><p>Paseo suave y menos tiempo sentado.</p></article><article><b>Jueves</b><p>20–30 min de cardio moderado.</p></article><article><b>Viernes</b><p>Segunda sesión de fuerza.</p></article><article><b>Fin de semana</b><p>Caminar, bici, bailar, piscina o naturaleza.</p></article></div><p><strong>Progresión:</strong> aumenta primero el tiempo, después la frecuencia y por último la intensidad. En fuerza, cuando completes las repeticiones con buena técnica y demasiado margen, aumenta ligeramente resistencia, repeticiones o series.</p></section>
  <div class="papef-sedentary"><span>🪑→🚶</span><div><h3>Entrenar no borra todo el tiempo sentado</h3><p>Reduce el sedentarismo. Sustituir parte del tiempo sentado por cualquier movimiento, incluso ligero, aporta beneficios.</p></div></div>
  <details class="papef-special"><summary>¿Y si tengo obesidad, diabetes, hipertensión, dolor o más de 65 años?</summary><p>Son precisamente perfiles en los que la prescripción individualizada puede ser especialmente útil. Si existe fragilidad o riesgo de caída, el programa debe combinar fuerza, equilibrio, marcha/resistencia y movilidad. Si una lesión o enfermedad impide entrenar con seguridad, primero se valora desde el recurso sanitario correspondiente.</p></details>
  <aside class="papef-safety"><span>!</span><div><strong>Antes de subir la intensidad</strong><p>Consulta si tienes síntomas con el esfuerzo, cardiopatía inestable, tensión no controlada, desmayos, cirugía reciente o una limitación importante. Detente ante dolor u opresión en el pecho, desmayo, confusión, debilidad súbita, palpitaciones mantenidas o falta de aire intensa y distinta de la habitual. Ante una urgencia, 112.</p></div></aside>
  <section class="papef-digital"><div><span>📱</span><h3>ActiVital</h3><p>Plataforma digital vinculada al PAPEF para diseñar y seguir programas de ejercicio y facilitar la coordinación entre salud y deporte.</p></div><a href="https://activital.ugr.es/" target="_blank" rel="noopener">Conocer ActiVital ↗</a></section>
  <details class="papef-sources"><summary>Documentos y fuentes utilizadas</summary><ul><li><b>Junta de Andalucía (2024).</b> Guía para profesionales: Recomendación de actividad física y prescripción de ejercicio físico para la salud.</li><li><b>Plan Andaluz de Prescripción de Ejercicio Físico (2023).</b></li><li><b>ActiVital.</b> Material del plan y plataforma PAPEF.</li><li><a href="https://www.who.int/publications/i/item/9789240015128" target="_blank" rel="noopener">OMS: Guidelines on physical activity and sedentary behaviour</a>.</li></ul><p>Contenido educativo adaptado a pacientes. Una prescripción real debe individualizarse según salud, medicación, capacidad física y preferencias.</p></details>
  </div></div>`; main.appendChild(section);
  const homeCard=[...document.querySelectorAll('.home-card')].find(c=>c.textContent.includes('Movimiento')); if(homeCard) homeCard.onclick=()=>showSection('ejercicio-papef');
}
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',initPapef); else initPapef();